name: pendidikan
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.13
  cupertino_icons: ^1.0.6
  http: ^1.1.0
   

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/siksakubur.png
    - assets/ancika.jpeg
    - assets/petualangan.jpg
    - assets/badarawuhi.jpg
    - assets/agaklain.jpeg
    - assets/sehidupsemati.jpg
    - assets/poto.jpg